[package]
name        = "datomic"
version     = "0.6.0"
edition     = "2024"
rust-version = "1.85"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/LiGoldragon/datomic"
description = "Datomic positional typed data over Protos Portion."
publish     = false

[dependencies]
protos = { git = "https://github.com/LiGoldragon/protos", rev = "49b1a5d261aa797109b2de98153a99859a539f97" }

[lib]
name = "datomic"
path = "src/lib.rs"

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
