[package]
name        = "datom"
version     = "0.2.0"
edition     = "2024"
rust-version = "1.85"
license     = "MIT OR Apache-2.0"
repository  = "https://github.com/LiGoldragon/datom"
description = "Datom text serialization and deserialization."
publish     = false

[dependencies]
protos = { git = "https://github.com/LiGoldragon/protos", rev = "bfea114c96eb548ceae17ab05da9c231a6412ba1" }

[lib]
name = "datom"
path = "src/lib.rs"

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
