//! The kinds `datom-codec-kinds.ethos` declares, generated by ethos-zero into
//! `generated/datom-codec-kinds.rs`, compile against this crate's types, and
//! each concrete type the declaration associates bears the generated kind:
//! the generated associations are compile-time assertions, so this target
//! building is the witness.

pub use datom_codec::{Budget, Datom, Error, ErrorKind, Form, Path, Positions, Potential};

#[path = "../generated/datom-codec-kinds.rs"]
mod kinds;

/// A path names a datom's place and branches to its children.
impl kinds::Branchable for Path {}
/// A budget is what composing spends from.
impl kinds::Budgeted for Budget {}
/// The positions of one struct form are read one after another.
impl kinds::Positional for Positions<'_> {}
/// A datom composed into a datom is that datom.
impl kinds::Composable for Datom {
    fn compose<N: kinds::Budgeted>(&self, _budget: N) -> Result<Self, Error> {
        Ok(self.clone())
    }
    fn compose_positions<N: kinds::Budgeted>(&self, _budget: N) -> Result<Self, Error> {
        Ok(self.clone())
    }
}
